
name: CI/CD
on:
  
  push:
    branches: [ "master" ]
   
jobs:
   
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/simplewhale:latest  
            
      - name: Run a one-line script
        run: echo Hello, world! 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
